name: firstworkflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get the Code
        uses: actions/checkout@v3
      - name: run index.js
        run: npm start
