name: firstworkflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: first-step
        run: echo "Hey from Github Actions!"
      - name: run index.js
        run: npm start
